image: fedora:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  script:
    # install build dependencies
    - dnf --quiet --assumeyes install flatpak flatpak-builder cmake make automake gcc gcc-c++
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.kde.Sdk//5.15 org.kde.Platform//5.15
    # get manifest from github repository
    - curl https://raw.githubusercontent.com/flathub/eu.scarpetta.PDFMixTool/master/eu.scarpetta.PDFMixTool.yaml > tmp.yaml
    # replace archive source with current directory
    - head -n -3 tmp.yaml > eu.scarpetta.PDFMixTool.yaml
    - "echo \"      - {type: dir, path: .}\" >> eu.scarpetta.PDFMixTool.yaml"
    # build and publish
    - flatpak-builder --repo=public --force-clean build-dir eu.scarpetta.PDFMixTool.yaml
    - flatpak build-update-repo public
  artifacts:
    paths:
      - public
  only:
    - master

# windows build
# image: fedora:latest
#
# build_mingw64:
#   stage: build
#   script:
#     - dnf --quiet --assumeyes install mingw64-gcc mingw64-gcc-c++ mingw64-binutils mingw64-headers mingw64-podofo mingw64-qt5-qtbase mingw64-qt5-qttools mingw64-qt5-qttools-tools cmake make
#     - export PATH=/usr/x86_64-w64-mingw32/bin:$PATH
#     - mkdir -p x86_64-w64-mingw32 mingw64-build; cd x86_64-w64-mingw32
#     - cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=/builds/${CI_PROJECT_PATH}/mingw64-build
#     - make; make install
#     - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll /builds/${CI_PROJECT_PATH}/mingw64-build/bin/
#     - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/lib/qt5 /builds/${CI_PROJECT_PATH}/mingw64-build/
#     - echo "[Paths]" > /builds/${CI_PROJECT_PATH}/mingw64-build/bin/qt.conf
#     - echo "Prefix = ../qt5" >> /builds/${CI_PROJECT_PATH}/mingw64-build/bin/qt.conf
#   artifacts:
#     expire_in: 14d
#     paths:
#       - ./mingw64-build
#   tags:
#     - shared
